---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - "1.8.x"
    - "1.9.x"
    - tip
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - staticcheck $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
